### ISSUE TITLE
testDomain目录写死导致“找不到config.yml”报错

### ISSUE THREAD

**Issue by Cosmos01** [Fatfish588/jmid2name-hoshino#1]
报找不到config.yml的问题只是因为你testDomain里面写死了目录吧。
https://github.com/Fatfish588/jmid2name-hoshino/blob/e821e7c688a58b40a9c173f845fc138ec65e7d5e/testDomain.py#L7

改成
`option = jmcomic.create_option(os.path.join(os.path.dirname(__file__), 'config.yml'))`
就可以了

**Comment by Fatfish588** [comment]
感谢提醒，已改正testDomain的路径问题。
